version: '2'
services:
    producer:
        build: ./producer
        ports: 
            - 8080:8888
        depends_on:
            - rabbitmq
        environment:
            - LOG_LEVEL=debug
            - LOG_FILE_NAME=api.log
            - LOG_TO_STDOUT=true
    rabbitmq:
        image: rabbitmq:3.6